#include "api/api_common.hpp"
#include "core/optional.hpp"
#include "on1x/on1x_module.h"
#include "on1x/on1x_capability.h"
#include "runtime/state.hpp"
#include "stdlib/args.hpp"
#include <cstdint>
#include <limits>
#include <bit>
namespace on1x::stdlib { namespace {
constexpr int W=64; On1x_Status bad(On1x_State*s,const char*m)noexcept{return push_api_error(s,m);}
On1x_Status bin(On1x_State*s,int a,const char*n,std::uint64_t(*f)(std::uint64_t,std::uint64_t))noexcept{if(!require_arity(s,a,2,n))return ON1X_ERR;Value x,y;if(!read_argument(s,1,x)||!read_argument(s,2,y)||!x.is_int()||!y.is_int())return bad(s,n);return stack_push(s,Value::integer(&s->gc,static_cast<std::int64_t>(f(static_cast<std::uint64_t>(x.as_int()),static_cast<std::uint64_t>(y.as_int())))))?ON1X_OK:ON1X_ERR;}
On1x_Status shift(On1x_State*s,int a,const char*n,bool arithmetic,bool left)noexcept{if(!require_arity(s,a,2,n))return ON1X_ERR;Value x,y;if(!read_argument(s,1,x)||!read_argument(s,2,y)||!x.is_int()||!y.is_int())return bad(s,n);if(y.as_int()<0||y.as_int()>=W)return stack_push(s,make_none(&s->gc,s->reserved))?ON1X_OK:ON1X_ERR;auto nbits=static_cast<unsigned>(y.as_int());std::uint64_t u=static_cast<std::uint64_t>(x.as_int());std::uint64_t out=left?u<<nbits:(arithmetic?static_cast<std::uint64_t>(x.as_int()>>nbits):u>>nbits);return stack_push(s,Value::integer(&s->gc,static_cast<std::int64_t>(out)))?ON1X_OK:ON1X_ERR;}
On1x_Status bitidx(On1x_State*s,int a,const char*n,int op)noexcept{if(!require_arity(s,a,2,n))return ON1X_ERR;Value x,y;if(!read_argument(s,1,x)||!read_argument(s,2,y)||!x.is_int()||!y.is_int())return bad(s,n);if(y.as_int()<0||y.as_int()>=W)return stack_push(s,make_none(&s->gc,s->reserved))?ON1X_OK:ON1X_ERR;auto mask=std::uint64_t{1}<<static_cast<unsigned>(y.as_int());auto u=static_cast<std::uint64_t>(x.as_int());if(op==0)return stack_push(s,make_some(&s->gc,s->reserved,Value::boolean((u&mask)!=0)))?ON1X_OK:ON1X_ERR;if(op==1)u|=mask;else if(op==2)u&=~mask;else u^=mask;return stack_push(s,make_some(&s->gc,s->reserved,Value::integer(&s->gc,static_cast<std::int64_t>(u))))?ON1X_OK:ON1X_ERR;}
const On1x_FnDesc fns[]={{"And",[](On1x_State*s,int a)noexcept{return bin(s,a,"Bit.And",[](auto x,auto y){return x&y;});}},{"Or",[](On1x_State*s,int a)noexcept{return bin(s,a,"Bit.Or",[](auto x,auto y){return x|y;});}},{"Xor",[](On1x_State*s,int a)noexcept{return bin(s,a,"Bit.Xor",[](auto x,auto y){return x^y;});}},{"Not",[](On1x_State*s,int a)noexcept{if(!require_arity(s,a,1,"Bit.Not"))return ON1X_ERR;Value x;if(!read_argument(s,1,x)||!x.is_int())return bad(s,"Bit.Not");return stack_push(s,Value::integer(&s->gc,static_cast<std::int64_t>(~static_cast<std::uint64_t>(x.as_int()))))?ON1X_OK:ON1X_ERR;}},{"Shl",[](On1x_State*s,int a)noexcept{return shift(s,a,"Bit.Shl",false,true);}},{"Shr",[](On1x_State*s,int a)noexcept{return shift(s,a,"Bit.Shr",false,false);}},{"Sar",[](On1x_State*s,int a)noexcept{return shift(s,a,"Bit.Sar",true,false);}},{"RotL",[](On1x_State*s,int a)noexcept{return bin(s,a,"Bit.RotL",[](auto x,auto y){auto n=static_cast<unsigned>(y%64);return (x<<n)|(x>>(64-n));});}},{"RotR",[](On1x_State*s,int a)noexcept{return bin(s,a,"Bit.RotR",[](auto x,auto y){auto n=static_cast<unsigned>(y%64);return (x>>n)|(x<<(64-n));});}},{"PopCount",[](On1x_State*s,int a)noexcept{if(!require_arity(s,a,1,"Bit.PopCount"))return ON1X_ERR;Value x;if(!read_argument(s,1,x)||!x.is_int())return bad(s,"Bit.PopCount");return stack_push(s,Value::integer(&s->gc,std::popcount(static_cast<std::uint64_t>(x.as_int()))))?ON1X_OK:ON1X_ERR;}},{"Clz",[](On1x_State*s,int a)noexcept{if(!require_arity(s,a,1,"Bit.Clz"))return ON1X_ERR;Value x;if(!read_argument(s,1,x)||!x.is_int())return bad(s,"Bit.Clz");auto u=static_cast<std::uint64_t>(x.as_int());return stack_push(s,Value::integer(&s->gc,u?std::countl_zero(u):64))?ON1X_OK:ON1X_ERR;}},{"Ctz",[](On1x_State*s,int a)noexcept{if(!require_arity(s,a,1,"Bit.Ctz"))return ON1X_ERR;Value x;if(!read_argument(s,1,x)||!x.is_int())return bad(s,"Bit.Ctz");auto u=static_cast<std::uint64_t>(x.as_int());return stack_push(s,Value::integer(&s->gc,u?std::countr_zero(u):64))?ON1X_OK:ON1X_ERR;}},{"Test",[](On1x_State*s,int a)noexcept{return bitidx(s,a,"Bit.Test",0);}},{"Set",[](On1x_State*s,int a)noexcept{return bitidx(s,a,"Bit.Set",1);}},{"Clear",[](On1x_State*s,int a)noexcept{return bitidx(s,a,"Bit.Clear",2);}},{"Toggle",[](On1x_State*s,int a)noexcept{return bitidx(s,a,"Bit.Toggle",3);}}};
const On1x_ModuleDesc desc{"Bit",ON1X_CAP_NONE,fns,sizeof(fns)/sizeof(*fns)};} const On1x_ModuleDesc* bit_module()noexcept{return &desc;} }
