add_executable(on1x_api_tests api_tests.cpp)
target_link_libraries(on1x_api_tests PRIVATE on1x)
target_include_directories(on1x_api_tests PRIVATE ${PROJECT_SOURCE_DIR}/include)
if(ON1X_ENABLE_FFI)
  target_compile_definitions(on1x_api_tests PRIVATE ON1X_TEST_EXPECT_FFI=1)
  add_executable(on1x_ffi_tests ffi_tests.cpp)
  target_link_libraries(on1x_ffi_tests PRIVATE on1x_ffi on1x_core on1x_gc)
  target_include_directories(on1x_ffi_tests PRIVATE ${PROJECT_SOURCE_DIR}/src)
  add_test(NAME on1x_ffi_tests COMMAND on1x_ffi_tests)
endif()
add_test(NAME on1x_api_tests COMMAND on1x_api_tests)
