#!/usr/bin/env python3
"""embed_sources.py — embed lib/on1x/*.on1x files into a C++ source."""

import os
import sys


def escape_c_string(text):
    """Escape a string for embedding as a C string literal."""
    result = []
    for ch in text:
        if ch == '\\':
            result.append('\\\\')
        elif ch == '"':
            result.append('\\"')
        elif ch == '\n':
            result.append('\\n')
        elif ch == '\r':
            result.append('\\r')
        elif ch == '\t':
            result.append('\\t')
        elif ord(ch) < 32:
            result.append('\\{:03o}'.format(ord(ch)))
        else:
            result.append(ch)
    return ''.join(result)


def generate(src_dir, output_path):
    """Read all .on1x files from src_dir and write the embedded C++ source."""
    files = []
    for root, dirs, filenames in os.walk(src_dir):
        for fn in sorted(filenames):
            if fn.endswith('.on1x'):
                full_path = os.path.join(root, fn)
                rel_path = os.path.relpath(full_path, start=src_dir)
                with open(full_path, 'r', encoding='utf-8') as f:
                    text = f.read()
                name = fn[:-5]  # strip .on1x
                files.append((name, rel_path, text))

    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)

    with open(output_path, 'w', encoding='utf-8') as out:
        out.write('// Auto-generated by tools/embed_sources.py. DO NOT EDIT.\n')
        out.write('// Embeds On1x standard library source files.\n\n')
        out.write('#include <cstddef>\n')
        out.write('#include "stdlib/embed.hpp"\n\n')
        out.write('// clang-format off\n')

        for name, _rel_path, text in files:
            escaped = escape_c_string(text)
            out.write('static const char src_{}[] = "{}";\n'.format(name, escaped))

        out.write('\nconst on1x::stdlib::EmbeddedSource embedded_sources[] = {\n')
        for name, rel_path, _text in files:
            out.write('    {{"{}", "{}", src_{}}},\n'.format(name, 'lib/on1x/' + rel_path, name))
        out.write('};\n\n')

        out.write('const std::size_t g_embedded_source_count = {};\n'.format(len(files)))
        out.write('// clang-format on\n')

    print('Generated {} with {} embedded source(s).'.format(output_path, len(files)))


def main():
    if len(sys.argv) < 2:
        print('Usage: embed_sources.py <src_dir> [output.cpp]', file=sys.stderr)
        sys.exit(1)

    src_dir = sys.argv[1]
    if not os.path.isdir(src_dir):
        print('Error: {} is not a directory'.format(src_dir), file=sys.stderr)
        sys.exit(1)

    output = sys.argv[2] if len(sys.argv) > 2 else 'src/stdlib/embedded_sources.gen.cpp'
    generate(src_dir, output)


if __name__ == '__main__':
    main()
