add_subdirectory(util)
add_subdirectory(gc)
add_subdirectory(core)
add_subdirectory(syntax)
add_subdirectory(sema)
add_subdirectory(ir)
add_subdirectory(runtime)
add_subdirectory(vm)
add_subdirectory(prelude)
add_subdirectory(stdlib)
if(ON1X_ENABLE_FFI)
  add_subdirectory(ffi)
endif()
add_subdirectory(api)
