#include "api/api_common.hpp"
#include "core/list.hpp"
#include "core/optional.hpp"
#include "core/string.hpp"
#include "core/tag_table.hpp"
#include "gc/roots.hpp"
#include "on1x/on1x_module.h"
#include "on1x/on1x_capability.h"
#include "runtime/state.hpp"
#include "stdlib/args.hpp"
#include "util/utf8.hpp"
#include <algorithm>
#include <charconv>
#include <cctype>
#include <cstdlib>
#include <sstream>
#include <string>
#include <string_view>
namespace on1x::stdlib { namespace {
On1x_Status bad(On1x_State*s,const char*m)noexcept{return push_api_error(s,m);}
bool args2(On1x_State*s,int a,const char*n,Value&x,Value&y){return require_arity(s,a,2,n)&&read_argument(s,1,x)&&read_argument(s,2,y);}
On1x_Status len(On1x_State*s,int a,bool bytes){if(!require_arity(s,a,1,bytes?"Str.ByteLen":"Str.CharLen"))return ON1X_ERR;Value v;if(!read_argument(s,1,v)||v.kind()!=Value::Kind::String)return bad(s,bytes?"Str.ByteLen":"Str.CharLen");auto text=string_view(as_string_const(v));if(bytes)return stack_push(s,Value::integer(&s->gc,static_cast<int64_t>(text.size())))?ON1X_OK:ON1X_ERR;size_t n=0;if(!utf8::codepoint_count(text,n))return bad(s,"Str.CharLen");return stack_push(s,Value::integer(&s->gc,static_cast<int64_t>(n)))?ON1X_OK:ON1X_ERR;}
On1x_Status at(On1x_State*s,int a)noexcept{if(!require_arity(s,a,2,"Str.At"))return ON1X_ERR;Value v,i;if(!args2(s,a,"Str.At",v,i)||v.kind()!=Value::Kind::String||!i.is_int())return bad(s,"Str.At");auto*t=as_string_const(v);int64_t idx=i.as_int();size_t n=0;utf8::codepoint_count(string_view(t),n);if(idx<0)idx+=static_cast<int64_t>(n);auto*cp=idx>=0?string_codepoint_at(&s->gc,t,idx):nullptr;return stack_push(s,cp?make_some(&s->gc,s->reserved,value_from_object(cp)):make_none(&s->gc,s->reserved))?ON1X_OK:ON1X_ERR;}
On1x_Status find(On1x_State*s,int a,bool reverse)noexcept{if(!require_arity(s,a,2,"Str.Find"))return ON1X_ERR;Value x,y;if(!args2(s,a,"Str.Find",x,y)||x.kind()!=Value::Kind::String||y.kind()!=Value::Kind::String)return bad(s,"Str.Find");auto s1=string_view(as_string_const(x));auto s2=string_view(as_string_const(y));size_t pos=reverse?s1.rfind(s2):s1.find(s2);if(pos==std::string_view::npos)return stack_push(s,make_none(&s->gc,s->reserved))?ON1X_OK:ON1X_ERR;size_t cp=0;for(size_t k=0;k<pos;){utf8::DecodeResult d;if(!utf8::decode_next(s1,k,d))break;k+=d.width;++cp;}return stack_push(s,make_some(&s->gc,s->reserved,Value::integer(&s->gc,static_cast<int64_t>(cp))))?ON1X_OK:ON1X_ERR;}
On1x_Status boolstr(On1x_State*s,int a,const char*n,bool(*f)(std::string_view,std::string_view))noexcept{if(!require_arity(s,a,2,n))return ON1X_ERR;Value x,y;if(!args2(s,a,n,x,y)||x.kind()!=Value::Kind::String||y.kind()!=Value::Kind::String)return bad(s,n);return stack_push(s,Value::boolean(f(string_view(as_string_const(x)),string_view(as_string_const(y)))))?ON1X_OK:ON1X_ERR;}
On1x_Status chars(On1x_State*s,int a,bool bytes)noexcept{if(!require_arity(s,a,1,bytes?"Str.Bytes":"Str.Chars"))return ON1X_ERR;Value v;if(!read_argument(s,1,v)||v.kind()!=Value::Kind::String)return bad(s,bytes?"Str.Bytes":"Str.Chars");auto text=string_view(as_string_const(v));auto*l=new_list(&s->gc);GcRoot r(l);if(bytes){for(unsigned char c:text)list_push(&s->gc,l,Value::integer(&s->gc,c));}else{for(size_t i=0;i<text.size();){utf8::DecodeResult d;if(!utf8::decode_next(text,i,d))return bad(s,"Str.Chars");auto*cp=new_string(&s->gc,text.substr(i,d.width));list_push(&s->gc,l,value_from_object(cp));i+=d.width;}}return stack_push(s,value_from_object(l))?ON1X_OK:ON1X_ERR;}
On1x_Status transform(On1x_State*s,int a,const char*n,int mode)noexcept{if(!require_arity(s,a,1,n))return ON1X_ERR;Value v;if(!read_argument(s,1,v)||v.kind()!=Value::Kind::String)return bad(s,n);std::string out(string_view(as_string_const(v)));if(mode<2){for(char&c:out)if(static_cast<unsigned char>(c)<128)c=static_cast<char>(mode?std::tolower(static_cast<unsigned char>(c)):std::toupper(static_cast<unsigned char>(c)));}else{size_t b=0,e=out.size();if(mode==2||mode==3)while(b<e&&std::isspace(static_cast<unsigned char>(out[b])))++b;if(mode==2||mode==4)while(e>b&&std::isspace(static_cast<unsigned char>(out[e-1])))--e;out=out.substr(b,e-b);}auto*t=new_string(&s->gc,out);return stack_push(s,value_from_object(t))?ON1X_OK:ON1X_ERR;}
On1x_Status repeat(On1x_State*s,int a)noexcept{if(!require_arity(s,a,2,"Str.Repeat"))return ON1X_ERR;Value v,n;if(!args2(s,a,"Str.Repeat",v,n)||v.kind()!=Value::Kind::String||!n.is_int())return bad(s,"Str.Repeat");if(n.as_int()<0)return stack_push(s,make_none(&s->gc,s->reserved))?ON1X_OK:ON1X_ERR;std::string out;for(int64_t i=0;i<n.as_int();++i)out+=string_view(as_string_const(v));auto*t=new_string(&s->gc,out);return stack_push(s,make_some(&s->gc,s->reserved,value_from_object(t)))?ON1X_OK:ON1X_ERR;}
On1x_Status toint(On1x_State*s,int a)noexcept{if(!require_arity(s,a,1,"Str.ToInt"))return ON1X_ERR;Value v;if(!read_argument(s,1,v)||v.kind()!=Value::Kind::String)return bad(s,"Str.ToInt");int64_t x=0;auto t=string_view(as_string_const(v));auto [p,e]=std::from_chars(t.data(),t.data()+t.size(),x);bool ok=e==std::errc{}&&p==t.data()+static_cast<ptrdiff_t>(t.size());return stack_push(s,ok?make_some(&s->gc,s->reserved,Value::integer(&s->gc,x)):make_none(&s->gc,s->reserved))?ON1X_OK:ON1X_ERR;}
On1x_Status fromint(On1x_State*s,int a)noexcept{if(!require_arity(s,a,1,"Str.FromInt"))return ON1X_ERR;Value v;if(!read_argument(s,1,v)||!v.is_int())return bad(s,"Str.FromInt");auto*t=new_string(&s->gc,std::to_string(v.as_int()));return stack_push(s,value_from_object(t))?ON1X_OK:ON1X_ERR;}
On1x_Status totag(On1x_State*s,int a)noexcept{if(!require_arity(s,a,1,"Str.ToTag"))return ON1X_ERR;Value v;if(!read_argument(s,1,v)||v.kind()!=Value::Kind::String)return bad(s,"Str.ToTag");return stack_push(s,value_from_object(s->tags.intern(&s->gc,string_view(as_string_const(v)))))?ON1X_OK:ON1X_ERR;}
const On1x_FnDesc fns[]={{"CharLen",[](On1x_State*s,int a)noexcept{return len(s,a,false);}},{"ByteLen",[](On1x_State*s,int a)noexcept{return len(s,a,true);}},{"At",at},{"Find",[](On1x_State*s,int a)noexcept{return find(s,a,false);}},{"RFind",[](On1x_State*s,int a)noexcept{return find(s,a,true);}},{"Contains",[](On1x_State*s,int a)noexcept{return boolstr(s,a,"Str.Contains",[](auto x,auto y){return x.find(y)!=std::string_view::npos;});}},{"StartsWith",[](On1x_State*s,int a)noexcept{return boolstr(s,a,"Str.StartsWith",[](auto x,auto y){return x.starts_with(y);});}},{"EndsWith",[](On1x_State*s,int a)noexcept{return boolstr(s,a,"Str.EndsWith",[](auto x,auto y){return x.ends_with(y);});}},{"Chars",[](On1x_State*s,int a)noexcept{return chars(s,a,false);}},{"Bytes",[](On1x_State*s,int a)noexcept{return chars(s,a,true);}},{"Upper",[](On1x_State*s,int a)noexcept{return transform(s,a,"Str.Upper",0);}},{"Lower",[](On1x_State*s,int a)noexcept{return transform(s,a,"Str.Lower",1);}},{"Trim",[](On1x_State*s,int a)noexcept{return transform(s,a,"Str.Trim",2);}},{"TrimStart",[](On1x_State*s,int a)noexcept{return transform(s,a,"Str.TrimStart",3);}},{"TrimEnd",[](On1x_State*s,int a)noexcept{return transform(s,a,"Str.TrimEnd",4);}},{"Repeat",repeat},{"ToInt",toint},{"FromInt",fromint},{"ToTag",totag},{"IsValidUtf8",[](On1x_State*s,int a)noexcept{if(!require_arity(s,a,1,"Str.IsValidUtf8"))return ON1X_ERR;Value v;if(!read_argument(s,1,v)||v.kind()!=Value::Kind::String)return bad(s,"Str.IsValidUtf8");return stack_push(s,Value::boolean(utf8::validate(string_view(as_string_const(v)))))?ON1X_OK:ON1X_ERR;}}};
const On1x_ModuleDesc desc{"Str",ON1X_CAP_NONE,fns,sizeof(fns)/sizeof(*fns)};} const On1x_ModuleDesc* str_module()noexcept{return &desc;} }
